
<Structures>
  <Structure Name="case" AutoFill="0" AutoCreate="1" DefaultHex="0" AutoDestroy="0" DoNotSaveLocal="0" RLECompression="1" AutoCreateStructsize="4096">
    <Elements>
      <Element Offset="0" Vartype="4 Bytes" Bytesize="4" RLECount="6" OffsetHex="00000000" DisplayMethod="unsigned integer"/>
      <Element Offset="24" Vartype="Byte" Bytesize="1" RLECount="2" OffsetHex="00000018" DisplayMethod="unsigned integer"/>
      <Element Offset="26" Vartype="4 Bytes" Bytesize="4" RLECount="3" OffsetHex="0000001A" DisplayMethod="unsigned integer"/>
    </Elements>
  </Structure>
</Structures>